= vertex-smpp

image:https://img.shields.io/badge/vert.x-4.2.5-purple.svg[link="https://vertx.io"]

== TODO
- Описать все фичи и сделать тестирование на каждую.
- Рефакторить имена пакетов.
- Сделать накрутку метрик в коде клиента и сервера. Перцентили?
- Сделать протухание по времени нахождения в очереди, так, чтобы данные в канале не портились. Сейчас хз, портятся они или нет.
- При переходе с клаудхопера request.createGenarickNack() наряду с request.createResponse().
- Реализовывать Outbind?
- Реализовывать JMX?
- При переходе с клаудхопера на свою кодовую базу сделать так, чтобы sequenceNumber у generic_nack мог быть null (тип поля при этом int, надо сделать отедльный флаг у этой Pdu, чтобы можно быо узнать было ли поле пустым или равно 0 на самом деле).
- Настройки сервера и клиента (кроме ssl) должны иметь возможность для обновления в рантайме (по ресту или еще как-то)
- Обязательно удалить `com.example.smpp.util.smpp.Gsm7BitCharset.Gsm7BitCharset`, он распространяется под Apache лицензией. Так же удалить все классы cloudhopper'а.
- тестирование хаосом: сделать docker-образ с эхо-сервером и использовать на нем `pumba netem --duration 60s --tc-image giadocker/iproute2 delay --destribution pareto --time 1000 --jetter 500 my-container-with-smmpp-echo-server`
- разобраться как масштабировать сервер и клиента
- Добавить лицензию https://www.apache.org/licenses/LICENSE-2.0 в LICENSE
- Демонстрационные реализации:
    * сделать аналог testcontainers
    * smpp-клиент и сервер, которы используются потоками вне эвент-лупа.
    * ismpp интерактивный smpp-клиент, где можно задавать запросы.
    * simple-smpp-server который умеет посылать deliver_sm в принимающие сессии и клиент, который делает сессии TRANSMITTER и RECEIVER.
    * email gateway, smpp -> EG -> smtp
    * smpp multiplexer, {smpp_1, smpp_2, ..., smpp_n} -> smpp-mux -> smpp-server
    * smpp-server-mock, может отрабатывать сценарии.
    * smpp-client-mock, может отрабатывать сценарии.

== Client Features
. [v] Bind to MC as `Transmitter`, `Receiver`, `Tranceiver` by calling bind method and pass host and port to it.
    .. [v] User can send `SystemId`, `Password`, `SystemType`, `Address` in bind_request.
    .. [v] Also, library sends interface version in bind_request.
. [v] User can set timeouts and callbacks.
. [v] User can send requests `submit_sm`, `deliver_sm`, `query_sm`, `data_sm` and [-] `generic_nack` as response. But user cannot send, `bind_receiver`, `bind_trancriver`, `bind_transmitter`, `unbind` and corresponding responses.
    .. [v] Each send returns future to user. By this future user can react to errors of sending by assigning callbacks.
. [-] Server keeps track of metrics for all sessions, which are available to user.

== Server Features
. [-] Each session keeps track of metrics, which are available to user.

== Usage
Клиентский код сам ведет пул сессий и управляет им из колбэков на события сессии.

Настройка логов для jvm, чтобы дебажить ssl `-Djavax.net.debug=ssl`.

Скорость записи в память
[source,bash]
----
$ dd if=/dev/zero of=/dev/null count=10000000
5120000000 bytes transferred in 9.106614 secs (562228720 bytes/sec)
----

== Building
To package library:
[source,bash]
----
./gradlew clean assemble
----

== Help

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]


