= vertex-smpp

image:https://img.shields.io/badge/vert.x-4.2.5-purple.svg[link="https://vertx.io"]

This application was generated using http://start.vertx.io

== TODO
- Делать все, то связано в версией протокола interfaceVersion.
- Сделать ошибки на старте более явными дописать обработчики ошибок с логированием.
- Сделать накрутку метрик в коде клиента и сервера. Перцентили?
- Сделать протухание по времени нахождения в очереди, так, чтобы данные в канале не портились. Сейчас хз, портятся они или нет.
- Удалить из ServerSessionConfigurator поля, недоступные на момент конфигурации, например password.
- Сделать возможность для пользователя реагировать на недоставку сообщений (+ `com.example.smpp.server.SmppSession.handleMessage` обрабатывать generick_nack - дописывать из него информацию в обвертку вокруг ответа); request.createGenarickNack() вместо createResponse
- Реализовывать Outbind?
- Реализовывать JMX?
- Настройки сервера и клиента (кроме ssl) должны иметь возможность для обновления в рантайме (по ресту или еще как-то)
- Обязательно удалить `com.example.smpp.util.smpp.Gsm7BitCharset.Gsm7BitCharset`, он распространяется под BSD лицензией. Так же удалить все классы cloudhopper'а.
- тестирование хаосом: сделать docker-образ с эхо-сервером и использовать на нем `pumba netem --duration 60s --tc-image giadocker/iproute2 delay --destribution pareto --time 1000 --jetter 500 my-container-with-smmpp-echo-server`
- разобраться как масштабировать сервер и клиента
- Добавить лицензию https://www.apache.org/licenses/LICENSE-2.0 в LICENSE
- Демонстрационные реализации:
    * ismpp интерактивный smpp-клиент, где можно задавать запросы.
    * simple-smpp-server который умеет посылать deliver_sm в принимающие сессии.
    * email gateway, smpp -> EG -> smtp
    * smpp multiplexer, {smpp_1, smpp_2, ..., smpp_n} -> smpp-mux -> smpp-server
    * smpp-server-mock, может отрабатывать сценарии.
    * smpp-client-mock, может отрабатывать сценарии.

== Features

== Usage
Клиентский код сам ведет пул сессий и управляет им из колбэков на события сессии.

Настройка логов для jvm, чтобы дебажить ssl `-Djavax.net.debug=ssl`.

== Building

To launch your tests:
[source,bash]
----
./gradlew clean test
----

To package your application:
[source,bash]
----
./gradlew clean assemble
----

To run your application:
[source,bash]
----
./gradlew clean run
----

== Help

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]


