= vertex-smpp

image:https://img.shields.io/badge/vert.x-4.2.5-purple.svg[link="https://vertx.io"]

This application was generated using http://start.vertx.io

== TODO
- Рефакторинг com.example.smpp.session.SessionCallbacksView.getOnUnexpectedResponse: PduResponse -> PduResponseContext
- Сделать накрутку метрик в коде клиента и сервера. Перцентили?
- В com/example/smpp/SmppSessionImpl.java:100 допилить aquire() с таймаутом
- Сделать протухание по времени нахождения в очереди, так, чтобы данные в канале не портились. Сейчас хз, портятся они или нет.
- Сделать возможность для пользователя реагировать на недоставку сообщений (+ `com.example.smpp.server.SmppSession.handleMessage` обрабатывать generick_nack - дописывать из него информацию в обвертку вокруг ответа)
- Реализовывать Outbind?
- Реализовывать JMX?
- Заставить работать по SSL
- Настройки сервера и клиента (кроме ssl) должны иметь возможность для обновления в рантайме (по ресту или еще как-то)
- Обязательно удалить `com.example.smpp.util.smpp.Gsm7BitCharset.Gsm7BitCharset`, он распространяется под BSD лицензией

== Features

== Usage
Клиентский код сам ведет пул сессий и управляет им из колбэков на события сессии.

== Building

To launch your tests:
[source,bash]
----
./gradlew clean test
----

To package your application:
[source,bash]
----
./gradlew clean assemble
----

To run your application:
[source,bash]
----
./gradlew clean run
----

== Help

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]


