= vertex-smpp

image:https://img.shields.io/badge/vert.x-4.2.5-purple.svg[link="https://vertx.io"]

This application was generated using http://start.vertx.io

== TODO
- сделать Pool в клиенте, клиент не закрывается, сесси внутри клиента не умирают, они имеют каждая свое время жизни.
- рефакторить колбэки и хэндлеры в Smpp*Worker и Smpp*Impl, сделать класс SessionCallbacks, где будут все колбэки для сессии.
- Сделать накрутку метрик в коде клиента и сервера. Перцентили?
- Разобраться с API для пользоватлея: где должны находиться меоды настройки и задаваться колбэки - в сессии или в клиенте/сервере?
- Сделать протухание по времени нахождения в очереди, так, чтобы данные в канале не порились.
- Сделать возможность для пользователя реагиривать на недоставку сообщений (+ `com.example.smpp.server.SmppSession.handleMessage` обрабатывать generick_nack - дописывать из него информацию в обвертку вокруг ответа)
- реализоваывать Outbind?
- реализовывать JMX?
- заставить работать по SSL
- настройки сервера и клиента (кроме ssl) должны иметь возможность для обновления в рантайме (по ресту или еще как-то)
- обязательно удалить `com.example.smpp.util.smpp.Gsm7BitCharset.Gsm7BitCharset`, он распространяется под BSD лицензией
- сделать API для колбэка проверки прав пользователя подключаться

== Features

== Usage
Клиентский код сам ведет пул сессий и управляет им из колбэков на события сессии.

== Building

To launch your tests:
[source,bash]
----
./gradlew clean test
----

To package your application:
[source,bash]
----
./gradlew clean assemble
----

To run your application:
[source,bash]
----
./gradlew clean run
----

== Help

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]


